start: stmt_list

stmt_list: stmt (SEP stmt)* SEP?
SEP: ";"

?stmt: call

call: NAME "(" [arg_list] ")"
arg_list: expr ("," expr)*

?expr: string
     | number
     | symbol
     | var
     | call

string : ESCAPED_STRING
number : SIGNED_NUMBER
symbol : ":" NAME
var    : "$" NAME

NAME: /[a-zA-Z_][a-zA-Z0-9_]*/

%import common.ESCAPED_STRING
%import common.SIGNED_NUMBER
%import common.WS
%ignore WS
